server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:mysql://mysql7.sqlpub.com:3312/lottery_jq?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&connectionCollation=utf8mb4_unicode_ci
    username: lottery_jq
    password: EiIF9VjsG6HJOTI5
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true